### ISSUE TITLE
php warning rmdir

### ISSUE THREAD

**Issue by WirthmU** [Cacti/plugin_gexport#7]
Gexport connects to the ftp site and does upload but there is the following php warning:

MEMUSE: 3 M, MESSAGE: Removing Local File 'graph_78.html'
2017-04-27 20:10:15 - EXPORT Removing Local File 'graph_64.html'
MEMUSE: 3 M, MESSAGE: Removing Local File 'graph_64.html'
2017-04-27 20:10:15 - EXPORT Removing Local Directory '/tmp/cacti-ftp-temp-/images'
MEMUSE: 3 M, MESSAGE: Removing Local Directory '/tmp/cacti-ftp-temp-/images'
PHP Warning:  Missing argument 2 for export_post_ftp_upload(), called in /var/www/cacti/plugins/gexport/functions.php on line 954 and defined in /var/www/cacti/plugins/gexport/functions.php on line 941
PHP Notice:  Undefined variable: stExportDir in /var/www/cacti/plugins/gexport/functions.php on line 943
2017-04-27 20:10:15 - EXPORT Removing Local File 'graph_62.html'
MEMUSE: 3 M, MESSAGE: Removing Local File 'graph_62.html'
PHP Warning:  rmdir(/tmp/cacti-ftp-temp-): Directory not empty in /var/www/cacti/plugins/gexport/functions.php on line 961
2017-04-27 20:10:16 - EXPORT STATS: ExportID:1 ExportDate:2017-04-27_20:10:16 ExportDuration:226.27 TotalGraphsExported:22
2017-04-27 20:10:16 - EXPORT MASTER STATS: Time:226.34 Exports:1 Exported:1

**Comment by cigamit** [comment]
Resolved.

**Comment by WirthmU** [comment]
I still get the same php warning in the log file but uploading works:
`14-07-2022 18:45:35 - CMDPHP PHP ERROR WARNING Backtrace: (/plugins/gexport/poller_export.php[107]:graph_export(), /plugins/gexport/functions.php[120]:run_export(), /plugins/gexport/functions.php[186]:export_ftp_php_execute(), /plugins/gexport/functions.php[1116]:export_ftp_php_uploaddir(), /plugins/gexport/functions.php[1170]:ftp_mkdir(), CactiErrorHandler()) `

**Comment by netniV** [comment]
That seems to be a separate issue and should be recorded separately.
